name: Auto Commit

on:
  schedule:
    # Run every 30 minutes
    - cron:  '* 2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_PAT }}

    - name: Create or update file
      run: echo "Last auto commit was at $(date)" > timestamp

    - name: Commit files
      run: |
        git config --local user.email "kenanbalija.dev@gmail.com"
        git config --local user.name "kenanbalija"
        git add -A
        git commit -m "Auto update" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_PAT }}
        branch: ${{ github.ref }}
