name: Auto Commit

on:
  schedule:
    # Run every 4 hours (6 times a day)
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create or update file
      run: echo "Last auto commit was at $(date)" > timestamp

    - name: Commit and push if it changed
      run: |
        git config user.name "kenanbalija"
        git config user.email "kenanbalija.dev@gmail.com"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto update"
        git push
